# Generated by Django 5.2.9

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SustainableGiftingItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sustainable_gifting_items',
                'ordering': ['order', 'created_at'],
                'indexes': [
                    models.Index(fields=['is_active'], name='sustainable_g_is_acti_idx'),
                    models.Index(fields=['order'], name='sustainable_g_order_idx'),
                ],
            },
        ),
    ]

