# Generated by Django 5.2.9 on 2025-12-11 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTestimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'text_testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoTestimonial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, help_text='Optional description or quote')),
                ('video_url', models.URLField(help_text='YouTube/Vimeo embed URL')),
                ('rating', models.IntegerField(default=5, help_text='Rating from 1 to 5')),
                ('location', models.CharField(blank=True, max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'video_testimonials',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='sustainablegiftingitem',
            new_name='sustainable_is_acti_189585_idx',
            old_name='sustainable_g_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='sustainablegiftingitem',
            new_name='sustainable_order_5f509b_idx',
            old_name='sustainable_g_order_idx',
        ),
        migrations.AddIndex(
            model_name='texttestimonial',
            index=models.Index(fields=['is_active'], name='text_testim_is_acti_630db0_idx'),
        ),
        migrations.AddIndex(
            model_name='texttestimonial',
            index=models.Index(fields=['order'], name='text_testim_order_da9f80_idx'),
        ),
        migrations.AddIndex(
            model_name='videotestimonial',
            index=models.Index(fields=['is_active'], name='video_testi_is_acti_f12e8a_idx'),
        ),
        migrations.AddIndex(
            model_name='videotestimonial',
            index=models.Index(fields=['order'], name='video_testi_order_9800da_idx'),
        ),
    ]
