# Generated by Django 5.2.9 on 2025-12-11 12:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_texttestimonial_videotestimonial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'about_us_sections',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active'], name='about_us_se_is_acti_20d754_idx'), models.Index(fields=['order'], name='about_us_se_order_d5e16e_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, help_text='Optional image for the blog post')),
                ('published_date', models.DateField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_posts',
                'ordering': ['-published_date', 'order', 'created_at'],
                'indexes': [models.Index(fields=['is_active'], name='blog_posts_is_acti_4e76a6_idx'), models.Index(fields=['published_date'], name='blog_posts_publish_4e4b9f_idx'), models.Index(fields=['order'], name='blog_posts_order_53a6f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='OurCommitmentSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'our_commitment_sections',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active'], name='our_commitm_is_acti_0ad914_idx'), models.Index(fields=['order'], name='our_commitm_order_ac806f_idx')],
            },
        ),
        migrations.CreateModel(
            name='OurStorySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'our_story_sections',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active'], name='our_story_s_is_acti_92ccb1_idx'), models.Index(fields=['order'], name='our_story_s_order_a21d65_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhotoGalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional title for the photo', max_length=200)),
                ('image_url', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'photo_gallery_items',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['is_active'], name='photo_galle_is_acti_c9a348_idx'), models.Index(fields=['order'], name='photo_galle_order_489eaf_idx')],
            },
        ),
    ]
