# Generated by Django 5.2.9 on 2025-12-07 15:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('category', models.CharField(choices=[('COOKIE', 'Cookie'), ('SNACK', 'Snack'), ('CAKE', 'Cake'), ('SWEET', 'Sweet'), ('HAMPER', 'Hamper')], max_length=20)),
                ('tags', models.CharField(max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('weight_grams', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='products_slug_5e91f2_idx'), models.Index(fields=['category'], name='products_categor_fce6e6_idx'), models.Index(fields=['is_available'], name='products_is_avai_39744e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['order', 'created_at'],
                'unique_together': {('product', 'order')},
            },
        ),
    ]
